name: trip_repository
description: Dart package which manages the trip domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.2
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0